mediaTypes:
  "text/markdown":
    suffixes: ["md", "mdx"]

outputFormats:
  MDX:
    mediaType: "text/markdown"
    isPlainText: true
    isHTML: false

outputs:
  home: ["HTML", "RSS", "MDX"]
  page: ["HTML", "MDX"]
  section: ["HTML", "RSS", "MDX"]
  taxonomy: ["HTML", "RSS", "MDX"]
  term: ["HTML", "RSS", "MDX"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true